"""
Auto-generated static data file mapping Country Names to FlagCDN codes.
Generated via FlagCDN API.
"""

COUNTRY_FLAGS = {
    "Afghanistan": "af",
    "Alabama": "us-al",
    "Alaska": "us-ak",
    "Albania": "al",
    "Algeria": "dz",
    "American Samoa": "as",
    "Andorra": "ad",
    "Angola": "ao",
    "Anguilla": "ai",
    "Antarctica": "aq",
    "Antigua and Barbuda": "ag",
    "Argentina": "ar",
    "Arizona": "us-az",
    "Arkansas": "us-ar",
    "Armenia": "am",
    "Aruba": "aw",
    "Australia": "au",
    "Austria": "at",
    "Azerbaijan": "az",
    "Bahamas": "bs",
    "Bahrain": "bh",
    "Bangladesh": "bd",
    "Barbados": "bb",
    "Belarus": "by",
    "Belgium": "be",
    "Belize": "bz",
    "Benin": "bj",
    "Bermuda": "bm",
    "Bhutan": "bt",
    "Bolivia": "bo",
    "Bosnia and Herzegovina": "ba",
    "Botswana": "bw",
    "Bouvet Island": "bv",
    "Brazil": "br",
    "British Indian Ocean Territory": "io",
    "British Virgin Islands": "vg",
    "Brunei": "bn",
    "Bulgaria": "bg",
    "Burkina Faso": "bf",
    "Burundi": "bi",
    "California": "us-ca",
    "Cambodia": "kh",
    "Cameroon": "cm",
    "Canada": "ca",
    "Cape Verde": "cv",
    "Caribbean Netherlands": "bq",
    "Cayman Islands": "ky",
    "Central African Republic": "cf",
    "Chad": "td",
    "Chile": "cl",
    "China": "cn",
    "Christmas Island": "cx",
    "Cocos (Keeling) Islands": "cc",
    "Colombia": "co",
    "Colorado": "us-co",
    "Comoros": "km",
    "Connecticut": "us-ct",
    "Cook Islands": "ck",
    "Costa Rica": "cr",
    "Cote D'Ivoire": "ci",
    "Croatia": "hr",
    "Cuba": "cu",
    "Cura\u00e7ao": "cw",
    "Cyprus": "cy",
    "Czechia": "cz",
    "C\u00f4te d'Ivoire (Ivory Coast)": "ci",
    "DR Congo": "cd",
    "Delaware": "us-de",
    "Denmark": "dk",
    "Djibouti": "dj",
    "Dominica": "dm",
    "Dominican Republic": "do",
    "Ecuador": "ec",
    "Egypt": "eg",
    "El Salvador": "sv",
    "England": "gb-eng",
    "Equatorial Guinea": "gq",
    "Eritrea": "er",
    "Estonia": "ee",
    "Eswatini (Swaziland)": "sz",
    "Ethiopia": "et",
    "European Union": "eu",
    "Falkland Islands": "fk",
    "Faroe Islands": "fo",
    "Fiji": "fj",
    "Finland": "fi",
    "Florida": "us-fl",
    "France": "fr",
    "French Guiana": "gf",
    "French Polynesia": "pf",
    "French Southern and Antarctic Lands": "tf",
    "Gabon": "ga",
    "Gambia": "gm",
    "Georgia": "us-ga",
    "Germany": "de",
    "Ghana": "gh",
    "Gibraltar": "gi",
    "Greece": "gr",
    "Greenland": "gl",
    "Grenada": "gd",
    "Guadeloupe": "gp",
    "Guam": "gu",
    "Guatemala": "gt",
    "Guernsey": "gg",
    "Guinea": "gn",
    "Guinea-Bissau": "gw",
    "Guyana": "gy",
    "Haiti": "ht",
    "Hawaii": "us-hi",
    "Heard Island and McDonald Islands": "hm",
    "Honduras": "hn",
    "Hong Kong": "hk",
    "Hungary": "hu",
    "Iceland": "is",
    "Idaho": "us-id",
    "Illinois": "us-il",
    "India": "in",
    "Indiana": "us-in",
    "Indonesia": "id",
    "Iowa": "us-ia",
    "Iran": "ir",
    "Iraq": "iq",
    "Ireland": "ie",
    "Isle of Man": "im",
    "Israel": "il",
    "Italy": "it",
    "Ivory Coast": "ci",
    "Jamaica": "jm",
    "Japan": "jp",
    "Jersey": "je",
    "Jordan": "jo",
    "Kansas": "us-ks",
    "Kazakhstan": "kz",
    "Kentucky": "us-ky",
    "Kenya": "ke",
    "Kiribati": "ki",
    "Korea Republic": "kr",
    "Kosovo": "xk",
    "Kuwait": "kw",
    "Kyrgyzstan": "kg",
    "Laos": "la",
    "Latvia": "lv",
    "Lebanon": "lb",
    "Lesotho": "ls",
    "Liberia": "lr",
    "Libya": "ly",
    "Liechtenstein": "li",
    "Lithuania": "lt",
    "Louisiana": "us-la",
    "Luxembourg": "lu",
    "Macau": "mo",
    "Madagascar": "mg",
    "Maine": "us-me",
    "Malawi": "mw",
    "Malaysia": "my",
    "Maldives": "mv",
    "Mali": "ml",
    "Malta": "mt",
    "Marshall Islands": "mh",
    "Martinique": "mq",
    "Maryland": "us-md",
    "Massachusetts": "us-ma",
    "Mauritania": "mr",
    "Mauritius": "mu",
    "Mayotte": "yt",
    "Mexico": "mx",
    "Michigan": "us-mi",
    "Micronesia": "fm",
    "Minnesota": "us-mn",
    "Mississippi": "us-ms",
    "Missouri": "us-mo",
    "Moldova": "md",
    "Monaco": "mc",
    "Mongolia": "mn",
    "Montana": "us-mt",
    "Montenegro": "me",
    "Montserrat": "ms",
    "Morocco": "ma",
    "Mozambique": "mz",
    "Myanmar": "mm",
    "Namibia": "na",
    "Nauru": "nr",
    "Nebraska": "us-ne",
    "Nepal": "np",
    "Netherlands": "nl",
    "Nevada": "us-nv",
    "New Caledonia": "nc",
    "New Hampshire": "us-nh",
    "New Jersey": "us-nj",
    "New Mexico": "us-nm",
    "New York": "us-ny",
    "New Zealand": "nz",
    "Nicaragua": "ni",
    "Niger": "ne",
    "Nigeria": "ng",
    "Niue": "nu",
    "Norfolk Island": "nf",
    "North Carolina": "us-nc",
    "North Dakota": "us-nd",
    "North Korea": "kp",
    "North Macedonia": "mk",
    "Northern Ireland": "gb-nir",
    "Northern Mariana Islands": "mp",
    "Norway": "no",
    "Ohio": "us-oh",
    "Oklahoma": "us-ok",
    "Oman": "om",
    "Oregon": "us-or",
    "Pakistan": "pk",
    "Palau": "pw",
    "Palestine": "ps",
    "Panama": "pa",
    "Papua New Guinea": "pg",
    "Paraguay": "py",
    "Pennsylvania": "us-pa",
    "Peru": "pe",
    "Philippines": "ph",
    "Pitcairn Islands": "pn",
    "Poland": "pl",
    "Portugal": "pt",
    "Puerto Rico": "pr",
    "Qatar": "qa",
    "Republic of Ireland": "ie",
    "Republic of the Congo": "cg",
    "Rhode Island": "us-ri",
    "Romania": "ro",
    "Russia": "ru",
    "Rwanda": "rw",
    "R\u00e9union": "re",
    "Saint Barth\u00e9lemy": "bl",
    "Saint Helena, Ascension and Tristan da Cunha": "sh",
    "Saint Kitts and Nevis": "kn",
    "Saint Lucia": "lc",
    "Saint Martin": "mf",
    "Saint Pierre and Miquelon": "pm",
    "Saint Vincent and the Grenadines": "vc",
    "Samoa": "ws",
    "San Marino": "sm",
    "Saudi Arabia": "sa",
    "Scotland": "gb-sct",
    "Senegal": "sn",
    "Serbia": "rs",
    "Seychelles": "sc",
    "Sierra Leone": "sl",
    "Singapore": "sg",
    "Sint Maarten": "sx",
    "Slovakia": "sk",
    "Slovenia": "si",
    "Solomon Islands": "sb",
    "Somalia": "so",
    "South Africa": "za",
    "South Carolina": "us-sc",
    "South Dakota": "us-sd",
    "South Georgia": "gs",
    "South Korea": "kr",
    "South Sudan": "ss",
    "Spain": "es",
    "Sri Lanka": "lk",
    "Sudan": "sd",
    "Suriname": "sr",
    "Svalbard and Jan Mayen": "sj",
    "Sweden": "se",
    "Switzerland": "ch",
    "Syria": "sy",
    "S\u00e3o Tom\u00e9 and Pr\u00edncipe": "st",
    "Taiwan": "tw",
    "Tajikistan": "tj",
    "Tanzania": "tz",
    "Tennessee": "us-tn",
    "Texas": "us-tx",
    "Thailand": "th",
    "Timor-Leste": "tl",
    "Togo": "tg",
    "Tokelau": "tk",
    "Tonga": "to",
    "Trinidad and Tobago": "tt",
    "Tunisia": "tn",
    "Turkey": "tr",
    "Turkmenistan": "tm",
    "Turks and Caicos Islands": "tc",
    "Tuvalu": "tv",
    "USA": "us",
    "Uganda": "ug",
    "Ukraine": "ua",
    "United Arab Emirates": "ae",
    "United Kingdom": "gb",
    "United Nations": "un",
    "United States": "us",
    "United States Minor Outlying Islands": "um",
    "United States Virgin Islands": "vi",
    "Uruguay": "uy",
    "Utah": "us-ut",
    "Uzbekistan": "uz",
    "Vanuatu": "vu",
    "Vatican City (Holy See)": "va",
    "Venezuela": "ve",
    "Vermont": "us-vt",
    "Vietnam": "vn",
    "Virginia": "us-va",
    "Wales": "gb-wls",
    "Wallis and Futuna": "wf",
    "Washington": "us-wa",
    "West Virginia": "us-wv",
    "Western Sahara": "eh",
    "Wisconsin": "us-wi",
    "Wyoming": "us-wy",
    "Yemen": "ye",
    "Zambia": "zm",
    "Zimbabwe": "zw",
    "\u00c5land Islands": "ax",
}
